name: flashcards
version: 0.0.1
synopsis: Backend for flashcard app
description: See README at <https://github.com/matthewchang/>
maintainer: Matthew Chang <mjchang07@gmail.com>
license: MIT
github: matthewchang/flashcards
category: Development
extra-source-files:
  - README.md

ghc-options: 
  - -Wall

dependencies:
  - base
  - aeson
  - aeson-extra >= 0.4.1.0
  - text
  - wai-middleware-static
  - bytestring
  - postgresql-simple
  - resource-pool
  - safe
  - string-conversions
  - servant
  - servant-server
  - sort
  - wai
  - warp
  - mtl
  - http-media
  - time
  - wai-extra
  - ghc-typelits-knownnat
  - superrecord

library:
  source-dirs: src
  exposed-modules:
    - Union
    - Lib
    - Tables
    - SuperRecordExtra
    - SchemaMatch

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - flashcards

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - hspec-discover
      - should-not-typecheck
      - flashcards
